### ISSUE TITLE
Is the upper plate required for mx switches

### ISSUE THREAD

**Issue by raveltan** [rtitmuss/torn#20]
Hello. I'm new in building keyboard.

Is the upper pcb (where the switches are attached to before in contatct with the main pcb) a required part of the build with mx switches?

**Comment by rtitmuss** [comment]
Hi, it is recommended to use a plate of you are using sockets to mount the MX switches. If you are soldering the MX switches then it's optional. The keyboard will feel more stiff/solid with a plate.

**Comment by zigotica** [comment]
I would warn against using 3 pin switches without plate, soldered or not, your keys will never be properly aligned.

**Comment by rtitmuss** [comment]
Thanks, good advice. I've only used 5 pin switches.

**Comment by raveltan** [comment]
Ah I see, thanks a lot for the info everybody.

Another question, is the plate required to be in form of pcb, or is it okay if we use other kind of materials (such as acrylics)

**Comment by rtitmuss** [comment]
You can use other materials. If you use acrylic I understand that 3mm is
the recommended thickness. I have also used 3d printed and steel plates.

**Comment by raveltan** [comment]
ah okay, thanks a lot for the help

**Comment by raveltan** [comment]
sorry everybody, but i have another question, I'm trying to print the plate and bottom plate as acrylic, is there any files in the gerber that contains the length information of the plate (or like file that can be used directly to print the acrylic), or should i do manual measurement of the main pcb? 

hahaha sorry if this is a stupid question

**Comment by keyboard-magpie** [comment]
There are not currently any laser cutting files- you will have to convert the files [here](https://github.com/rtitmuss/torn/tree/master/case/PCB%20Case)

**Comment by raveltan** [comment]
Okay thanks😁
