### ISSUE TITLE
Connection both sides with jumper

### ISSUE THREAD

**Issue by raveltan** [rtitmuss/torn#21]
hello everybody, sorry if this is a stupid question, but because i'm not able to find the specific model of the trrs jack component here in Indonesia, i am wondering if its possible to conect both side of the keyboard using normal jumper wire and some header pins

**Comment by rtitmuss** [comment]
Yes you can. For an example see the travel case instructions https://github.com/rtitmuss/torn/tree/master/case/Travel%20Case#step-4.

**Comment by raveltan** [comment]
ah okay, thank a lot for the help
