### ISSUE TITLE
Cover.dxf file has duplicate cut lines

### ISSUE THREAD

**Issue by gorbachev** [rtitmuss/torn#7]
I just put in an order for the acrylic cover with Ponoko, and they're telling me the Cover.dxf contains duplicate cut lines in both top corners. This causes the laser cutter to cut the same location twice, which is likely to cause problems with the end result.

I found out 6 identical lines by converting the DXF file into an SVG using Inkscape, grepping for 'd="m', then sorting them alphabetically. I manually removed them from the SVG file and resubmitted it to Ponoko. Even after that, they're saying there are double lines there.

**Comment by rtitmuss** [comment]
Did you find a fix for this? If not I can take a look at this in a week or two.

**Comment by gorbachev** [comment]
I did not. I loaded the file to Inkscape, and combined the paths, as recommended as a solution to similar issues on the Internets, but even that didn't remove all the double/overlapping lines according to Ponoko.

My order should be arriving later this week, so I'll find out then if it actually causes any visible issues. Ponoko did manufacture it just fine and they didn't notify me with any issues prior to shipping the order, so I'm assuming it's actually just fine.

**Comment by bromanko** [comment]
I pulled the SVGs into Figma and there is a lot of "noise" in the outlines. (See image.) My guess is that these were drawn in KiCad and then exported which didn't produce the cleanest vectors. I'm going to redraw the outline shapes and try to get those cut. If they work I can upload the files.  

<img width="914" alt="image" src="https://user-images.githubusercontent.com/160158/103673504-45f4b400-4f43-11eb-869e-572a69a351df.png">

**Comment by gorbachev** [comment]
Uh, yea, that doesn't look great.

I just received my order from Ponoko and I can't see anything wrong with the plates they cut for me. This is using an SVG file I saved after I deleted the identical lines from the design. There were overlapping lines still in the file.

**Comment by rtitmuss** [comment]
I have uploaded an improved cover.dxf that is cleaner:

https://github.com/rtitmuss/torn/commit/a0d7ace852e73de42067a03e02603ebb7805a3f0
